### ISSUE TITLE
直接运行项目代码错误

### ISSUE THREAD

**Issue by 1236897** [tianyong90/we-vue#40]
## 我用的环境
已经拉去新代码，但是运行npm install 后，运行npm run dev 依然会出现一下报错
OS:
浏览器：
webpack 版本：
we-vue 版本：

## 问题、现象以及重现步骤
Compiling
✔ success webpack compiled in 23s 397ms

 ERROR  Failed to compile with 2 errors                                 15:40:56

 error  in ./example/assets/images/icon_tabbar.png

Module build failed: TypeError: Cannot read property 'context' of undefined
    at Object.loader (/Users/ming/Desktop/Dev/projects/we-vue/node_modules/file-loader/dist/index.js:34:48)
    at Object.loader (/Users/ming/Desktop/Dev/projects/we-vue/node_modules/url-loader/dist/index.js:61:19)

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/eslint-loader??ref--5-0!./example/pages/tabbar.vue?vue&type=script&lang=js 27:0-58 32:18-28
 @ ./example/pages/tabbar.vue?vue&type=script&lang=js
 @ ./example/pages/tabbar.vue
 @ ./example sync ^\.\/pages.*\.vue$
 @ ./example/router/index.js
 @ ./example/main.js
 @ multi (webpack)-dev-server/client?http://ip:8080 webpack/hot/dev-server ./example/main.js

 error  in ./example/assets/iconfont/iconfont.svg?t=1505363621205

Module build failed: TypeError: Cannot read property 'context' of undefined
    at Object.loader (/Users/ming/Desktop/Dev/projects/we-vue/node_modules/file-loader/dist/index.js:34:48)
    at Object.loader (/Users/ming/Desktop/Dev/projects/we-vue/node_modules/url-loader/dist/index.js:61:19)

 @ ./node_modules/css-loader??ref--13-1!./node_modules/postcss-loader/lib??ref--13-2!./example/assets/iconfont/iconfont.css 7:8805-8846
 @ ./example/assets/iconfont/iconfont.css
 @ ./example/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.111:8080 webpack/hot/dev-server ./example/main.js

**Comment by tianyong90** [comment]
能否说下具体使用环境？看到前一个被关闭的 issue 也是这个问题，之后做了哪些尝试？

**Comment by gybin02** [comment]
也是 执行 npm run dev 失败： 
步骤:
1. git clone 
2. npm install 安装依赖
3. 执行npm run dev.

log:

>  we-vue@2.1.2 build:entry /Users/tony/Documents/github/we-vue
> node build/bin/build-entry.js

> [build entry] DONE: /Users/tony/Documents/github/we-vue/src/index.js
 TypeError: Object.values is not a function
    at hasRunning (/Users/tony/Documents/github/we-vue/node_modules/webpackbar/dist/index.js:55:33)
    at WebpackBarPlugin.render (/Users/tony/Documents/github/we-vue/node_modules/webpackbar/dist/index.js:178:9)
    at invokeFunc (/Users/tony/Documents/github/we-vue/node_modules/lodash/lodash.js:10333:23)
    at leadingEdge (/Users/tony/Documents/github/we-vue/node_modules/lodash/lodash.js:10343:26)
    at WebpackBarPlugin.debounced [as _render] (/Users/tony/Documents/github/we-vue/node_modules/lodash/lodash.js:10410:20)
    at WebpackBarPlugin.updateProgress (/Users/tony/Documents/github/we-vue/node_modules/webpackbar/dist/index.js:156:10)
    at WebpackBarPlugin.handler (/Users/tony/Documents/github/we-vue/node_modules/webpackbar/dist/index.js:68:55)
    at compiler.hooks.compilation.tap.compilation (/Users/tony/Documents/github/we-vue/node_modules/webpack/lib/ProgressPlugin.js:126:5)
    at SyncHook.eval (eval at create (/Users/tony/Documents/github/we-vue/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:9:1)
    at SyncHook.lazyCompileHook [as _call] (/Users/tony/Documents/github/we-vue/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.newCompilation (/Users/tony/Documents/github/we-vue/node_modules/webpack/lib/Compiler.js:438:26)
    at hooks.beforeCompile.callAsync.err (/Users/tony/Documents/github/we-vue/node_modules/webpack/lib/Compiler.js:474:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/tony/Documents/github/we-vue/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/tony/Documents/github/we-vue/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (/Users/tony/Documents/github/we-vue/node_modules/webpack/lib/Compiler.js:469:28)
    at compiler.hooks.watchRun.callAsync.err (/Users/tony/Documents/github/we-vue/node_modules/webpack/lib/Watching.js:77:18)

**Comment by tianyong90** [comment]
说下具体环境。
操作系统、Node 版本 ...
我这没法复现，提供下具体信息才好调试。
